name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows-dll:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build DLL
        run: cl /LD encrypt_1.cpp /Feencrypt1.dll

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: encrypt1
          path: encrypt1.dll
