name: Build DLL

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-windows-dll:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: microsoft/setup-vs@v1

      - name: Build DLL
        shell: cmd
        run: cl /LD encrypt_1.cpp /Feencrypt1.dll

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypt1
          path: encrypt1.dll
