name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows-dll:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Developer Command Prompt and Build DLL
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cl /LD encrypt_1.cpp /Feencrypt1.dll

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypt1
          path: encrypt1.dll
